title: Monica Vargas
logo: https://github.com/monik719/Portafolio/blob/main/WhatsApp%20Image%202024-11-21%20at%209.39.41%20PM.jpeg
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
