title: Monica Vargas
logo: foto.jpeg
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
include:
  - assets
  - README.md
